plugins:
  http_probe:
    name: http_probe
    config:
      endpoints:
        - url: "http://localhost:8080"               # 目标 URL
          method: "GET"                           # HTTP 方法
          # headers:                               # 请求头
          #   Content-Type: "application/json"
          #   Authorization: "Bearer your_token"
          timeout: 30                             # 超时时间（秒）
          expectedStatusCode: 200                 # 预期的 HTTP 状态码
          storageConfig:                          # 存储配置
            type: InKube
            inKube:
             #annotationKey: http_probe
              target:
                  group:  game.kruise.io
                  version: v1alpha1
                  resource: gameservers
                  name: ${SELF:POD_NAME}
                  namespace: ${SELF:POD_NAMESPACE}
              jsonPath: /spec/opsState
              markerPolices:
                - state: idle
                  labels:
                    gameserver-idle: 'true'
                  annotations:
                    controller.kubernetes.io/pod-deletion-cost: '-10'
                - state: allocated
                  labels:
                    gameserver-idle: 'false'
                  annotations:
                    controller.kubernetes.io/pod-deletion-cost: '10'

          # jsonPathConfig:                         # JSONPath 配置
          #   path: "$.store.book[*].author"
          #   expectedValue: "John Doe"
    bootOrder: 1
  hot_update:
    name: hot_update
    config:
      loadPatchType: "signal"
      fileDir: "/app/downloads"
      signal:
        signalName: "SIGHUP"
        processName: "nginx: master process nginx"
      storageConfig: # 存储配置
        type: InKube
        inKube:
          annotationKey: "sidecar.vke.volcengine.com/hot-update-result"

    bootOrder: 1

restartPolicy: Always
resources:
  CPU: 100m
  Memory: 128Mi
sidecarStartOrder: Before
