apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
metadata:
  name: veloren
  namespace: default
spec:
  replicas: 3
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
  gameServerTemplate:
    spec:
      containers:
        - image: ai-test-cn-shanghai.cr.volces.com/agones-images/veloren/server-cli:weekly
          name: veloren