plugins:
  http_probe:
    name: http_probe
    config:
      endpoints:
        - url: "http://example.com"               # 目标 URL
          method: "GET"                           # HTTP 方法
          headers:                               # 请求头
            Content-Type: "application/json"
            Authorization: "Bearer your_token"
          timeout: 30                             # 超时时间（秒）
          expectedStatusCode: 200                 # 预期的 HTTP 状态码
          storageConfig:                          # 存储配置
            connectionString: "your_connection_string"
            databaseName: "your_database_name"
          jsonPathConfig:                         # JSONPath 配置
            path: "$.store.book[*].author"
            expectedValue: "John Doe"
        - url: "http://another-example.com"       # 目标 URL
          method: "POST"                          # HTTP 方法
          headers:                               # 请求头
            Content-Type: "application/xml"
          timeout: 20                             # 超时时间（秒）
          expectedStatusCode: 201                 # 预期的 HTTP 状态码
          storageConfig:                          # 存储配置
            connectionString: "another_connection_string"
            databaseName: "another_database_name"
          jsonPathConfig:                         # JSONPath 配置
            path: "$.store.book[*].title"
            expectedValue: "Another Title"

    bootOrder: 1
restartPolicy: Always
resources:
  CPU: 100m
  Memory: 128Mi
sidecarStartOrder: Before
