---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - serverless.vke.volcengine.com
  resources:
  - sidecarconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serverless.vke.volcengine.com
  resources:
  - sidecarconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - serverless.vke.volcengine.com
  resources:
  - sidecarconfigs/status
  verbs:
  - get
  - patch
  - update
