# sidecarset.yaml
apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: add-okg-sidecar
spec:
  selector:
    matchLabels:
      game.kruise.io/owner-gss: veloren
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
  containers:
  - name: game-sidecar
    image: ai-demo-image-cn-beijing.cr.volces.com/game-images/okg-sidecar:v4
    volumeMounts:
    - mountPath: /opt/sidecar
      name: config-volume
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  volumes:
  - configMap:
      defaultMode: 420
      name: sidecar-configmap
    name: config-volume