apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hot-update-demo1
  namespace: default
spec:
  serviceName: "hot-update-demo"
  replicas: 1
  selector:
    matchLabels:
      app: hot-update-demo
  template:
    metadata:
      annotations:
        vci.volcengine.com/tls-enable: "false"
        vke.volcengine.com/burst-to-vci: enforce #该方案可以在 VCI 中使用
      labels:
        app: hot-update-demo
    spec:
      containers:
        - image: cr-demo-cn-beijing.cr.volces.com/guox/2048
          imagePullPolicy: Always
          name: game-room-r9001
          ports:
            - containerPort: 80
              name: game
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/www/html
              name: share-data # 持久化存储共享目录
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: share-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-result
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/volcengine-loadbalancer-address-type: PUBLIC
    service.beta.kubernetes.io/volcengine-loadbalancer-bandwidth: "10"
    service.beta.kubernetes.io/volcengine-loadbalancer-billing-type: "2"
    service.beta.kubernetes.io/volcengine-loadbalancer-eip-billing-type: "3"
    service.beta.kubernetes.io/volcengine-loadbalancer-health-check-flag: "off"
    service.beta.kubernetes.io/volcengine-loadbalancer-ip-version: ipv4
    service.beta.kubernetes.io/volcengine-loadbalancer-isp-type: BGP
    service.beta.kubernetes.io/volcengine-loadbalancer-master-zone-id: cn-beijing-a
    service.beta.kubernetes.io/volcengine-loadbalancer-modification-protection-status: ConsoleProtection
    service.beta.kubernetes.io/volcengine-loadbalancer-name: lzp-game
    service.beta.kubernetes.io/volcengine-loadbalancer-pass-through: "true"
    service.beta.kubernetes.io/volcengine-loadbalancer-project-name: default
    service.beta.kubernetes.io/volcengine-loadbalancer-scheduler: wrr
    service.beta.kubernetes.io/volcengine-loadbalancer-slave-zone-id: cn-beijing-b
    service.beta.kubernetes.io/volcengine-loadbalancer-spec: small_1
  name: lzp-game-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: hot
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: hot-update-demo
  sessionAffinity: None
  type: LoadBalancer

